# Theme
theme: jekyll-theme-midnight

# Credentials
title: Forest Notes
description: Tips, tricks, cheatsheets
baseurl: "/"
url: "https://iamzaychik.github.io/"
email: "zaychik.info@gmail.com"
github_username: iamzaychik

# Posts
permalink: none

# Misc
google_analytics: false
show_downloads: false
show_repository: false
