theme: jekyll-theme-midnight

title: Зайчик пише
description: Tips, tricks, cheatsheets
baseurl: "/"
url: "https://zaychik.tk"
email: "zaychik.info@gmail.com"
github_username: iamzaychik
show_downloads: false
google_analytics: false

exclude:
  - rebuild_indexes.sh