theme: jekyll-theme-slate

title: Зайчик пише
description: Tips, tricks, cheatsheets
baseurl: "/"
url: "https://zaychik.tk"
email: "zaychik.info@gmail.com"
github_username: iamzaychik

exclude:
  - rebuild_indexes.sh