# Theme
theme: jekyll-theme-midnight

# Credentials
title: Зайчик пише
description: Tips, tricks, cheatsheets
baseurl: "/"
url: "https://zaychik.tk"
email: "zaychik.info@gmail.com"
github_username: iamzaychik

# Posts
permalink: none

# Misc
google_analytics: false
show_downloads: false
show_repository: false
